// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMkAOf8_Lpn6AgVOBgK7ed7X5F0RMe0-0',
    appId: '1:530015148924:web:81dd57ec08073ab3b9e2f9',
    messagingSenderId: '530015148924',
    projectId: 'crudapp-d1749',
    authDomain: 'crudapp-d1749.firebaseapp.com',
    storageBucket: 'crudapp-d1749.appspot.com',
    measurementId: 'G-0KBBFG0V44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByXQ3ye6DRp226yq750BsJgE2j-7W-Rb4',
    appId: '1:530015148924:android:cac51d358e2b1ae6b9e2f9',
    messagingSenderId: '530015148924',
    projectId: 'crudapp-d1749',
    storageBucket: 'crudapp-d1749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtItQKsEc9sPFpnKwfC56TbM9PVn4IYQ',
    appId: '1:530015148924:ios:c6caecd5d6a5b508b9e2f9',
    messagingSenderId: '530015148924',
    projectId: 'crudapp-d1749',
    storageBucket: 'crudapp-d1749.appspot.com',
    iosBundleId: 'com.example.crud3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtItQKsEc9sPFpnKwfC56TbM9PVn4IYQ',
    appId: '1:530015148924:ios:66b04cccb92d5696b9e2f9',
    messagingSenderId: '530015148924',
    projectId: 'crudapp-d1749',
    storageBucket: 'crudapp-d1749.appspot.com',
    iosBundleId: 'com.example.crud3.RunnerTests',
  );
}
